
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'New World VOD Analysis',
  description: 'A tool generated by Rafael Ramalho - Raisingz',
}

export default function Finished() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1>Finished vods:</h1>
    </main>
  )
}
